image_topic: "/usb_cam/image_raw"
save_subdir: "camera_snapshots"
aruco_dictionary: "DICT_6X6_250"
squares_horizontally: 5
squares_vertically: 7
square_length: 0.03
marker_length: 0.015
total_page_length_px: 640
margin_px: 20
